R2300:
  transport: "udp"
  scanner_ip: "169.254.236.10"
  start_angle: -450000
  max_num_points_scan: 0
  packet_type: "C1"
  scan_topic: "/236/cloud"
  frame_id: "scanner"
  watchdogtimeout: 60
  watchdog: false
